version: '3'
services: 

  # Configure a database service in a container
  database:
    image: sameersbn/postgresql
    container_name: maso
    environment:
    - DB_NAME=maso-local,maso-test
    - PG_TRUST_LOCALNET=true
    ports:
    - 5432:5432
    volumes:
    - database-storage:/var/lib/postgresql

volumes:
  database-storage:
