version: '3'
services: 

  # Configure a database service in a container
  database:
    image: sameersbn/postgresql:latest
    container_name: maso-db
    environment:
    - DB_NAME=maso-local,maso-test
    - PG_TRUST_LOCALNET=true
    ports:
    - 5432:5432

  # Configure a redis server in a container
  redis:
    image: redis:latest
    container_name: maso-redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
    - 6379:6379

